# Generated by Django 2.2.2 on 2019-07-16 13:30

from django.db import migrations


def forward_func (apps, schema_editor):
    my_model = apps.get_model("myapp", "MyModel")
    db_alias = schema_editor.connection.alias
    with open("data.txt", "r") as data:
        for line in data.readlines():
            first_name, last_name, age, experience = line.split()
            my_model.objects.using(db_alias).bulk_create([
                my_model(first_name=first_name, last_name=last_name, age= int(age) if age != "NULL" else None,
                         experience=int(experience) if experience != "NULL" else None)
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward_func),
    ]
