# Generated by Django 2.2.2 on 2019-07-16 15:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_my_migration'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mymodel',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
